HackClubRAIT/HackClubRAIT-Website.github.io

styles.css
Made the navbar fixed at top while scrolling
closes: #1 
=> Made the navbar fixed at the top

styles.css
Made Team section responsive by adding media queries
closes: #5 
=> Made Teams section responsive

.vscode/settings.json, styles.css
changed the scrollbar and also made changes to the height of the homepage
https://user-images.githubusercontent.com/74983536/135582895-f64daf …
=> issue #6 Scrollbar-homepage changes

projects.html
changed style in project cards in projects page and centralized tags in project cards 
closes: #24 
=> styled projects page

index.html, styles.css
spaced sections correctly in order to look better.
added logo at title bar.
added few animations.
closes: #issue_number
=> Spacing the sections to full screen and few more updates

index.html, styles.css
I made the home page banner responsive
closes: #47 
-   [ ] I have commented my code, particularly in hard-to-understand areas.
Responsive -
=> home banner made responsive

burger.js, contact.html, contributer.html, index.html, opportunity.html, projects.html, styles.css, team.html
I have made the site responsive which includes navbar,team, projrcts, opportunities and contact-form.
closes: #49
=> I have made the site responsive

index.html, styles.css
added hover effects to navbar links
closes: #33 
=> hover effects added

contact.html, contributer.html, index.html, opportunity.html, projects.html, styles.css, team.html
1. Updated contributors page.
- Added hover effects with nice transitions.
- Added names
2. Updated navbar.
- Clicking logo takes you back to home page (index.html).
- Added hover animation.
- Similar issues were already there, the code is conflict-free and can be merged.
3. Updated Contact Us Form
- Added sleek animations and made the form responsive for all screen resolutions.
closes: #63 
-   [x] I have  checked there aren't other open [Pull Requests](https://github.com/HackClubRAIT/HackClubRAIT-Website.github.io …
=> Updated Contributors Page (Issue #63)

index.html, styles.css
Made content mobile responsive in main page.
closes: #64 
=> Made content responsive in mainpage

styles.css
I have successfully removed scrollbar for mobile view i have attached screenshots of before and after 
closes: #107 
before
after
=> scrollbar removed for mobile view

styles.css
updated the hover effect, now looking nice 
closes: #106 
=> updated Hover effects on icons in team section

styles.css
Hover effects on icons in team section
closes: #106
=> Hover effects on icons in team section

blogs.html, contact.html, contributer.html, index.html, opportunity.html, projects.html, team.html
I have changed the HTML of Navbar in every page. I have basically corrected the position of active class. 
closes: #issue_number 114 (There is a issue in Navbar Even when we are going to a different page HOME is highlighted)
- …
=> ISSUE NO : 114 ISSUE : There is a issue in Navbar Even when we are going to a different page HOME is highlighted 

index.html, styles.css
Added animated background. The transparent boxes will float upwards.
=> Added Animated Background

styles.css
Solved the underline problem.
Remove this line and add a description
closes: #132 
=> Solved the underline problem.

opportunity.html, styles.css
I have added/changed the following things
- Font
- Styled the cards 
- Made the square logos into circular ones
- fixed few typos
closes: #130 
=> issue #130 Oppurtunity cards css enhanced

styles.css, team.html
I have Improved the cards UI in the teams section and made it responsive too
closes: #125
=> Improved the cards UI in the teams section and made it responsive too

index.html, styles.css
I have added a discord icon in the footer
closes: #140 
=> Added discord icon in the footer

contact.html, styles.css
@Chaitalishetty please review it!!
=> issue #131

styles.css
Made the image in opportunities tab responsive.
Made the image in opportunities tab responsive.
closes: #139 
=> Made the image in opportunities tab responsive.

opportunity.html
Solved #150  number issue.
Solved #150  number issue.
closes: #150 
=> Solved #150  number issue.

styles.css
Fixed image overlapping in 2nd and 3rd section of HomePage in mobile view.
closes: #145 
=> Fixed image overlapping in 2nd and 3rd section of HomePage in mobile view.

styles.css
Created smooth scrolling for navigate to top button
closes: #153 
=> Added smooth scrolling

.vscode/settings.json, contributer.html, styles.css
I have added a SearchBar in the contributors page
closes: #156 
=> Added a SearchBar in the contributors page

blogs.html, styles.css
Enhance the blogs page UI.
closes: #159 
=> Enhance blogs page
